# Generated by Django 4.0.5 on 2022-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
