# Generated by Django 4.0.5 on 2022-06-23 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_genre_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=255)),
                ('tmdb_movie_id', models.PositiveBigIntegerField()),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.PositiveBigIntegerField()),
                ('actors', models.CharField(blank=True, max_length=500, null=True)),
                ('trailer', models.CharField(blank=True, max_length=100, null=True)),
                ('favourited', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
