# Generated by Django 4.0.5 on 2022-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tldr',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
